### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by ssal23** [jflancer/bigballR#14]
How is Garbage Time defined when I'm using the get_lineups function?

**Comment by ssal23** [comment]
Curious about the exact parameters here.

**Comment by jflancer** [comment]
I use a fairly similar definition to Cleaning The Glass. Once a game reaches garbage time, that threshold will apply for the rest of the game, even if a team comes back or falls out of the definition.

If the score differential meets the following criteria:

Score Diff >= 25 & Game_Seconds >= 1800,
Score Diff >= 20 & Game_Seconds >= 2100,
Score Diff >= 15 & Game_Seconds >= 2280

If <= 3 starters are still remaining in the game
