### ISSUE TITLE
Issues with Lineup Data

### ISSUE THREAD

**Issue by mattrhein** [jflancer/bigballR#15]
Hi there,
Was pulling some lineup data in the same way you published on your Github. I noticed a few issues: data that was previously pulling successfully now has 0's in all fields and the same players appearing in multiple position spots most noticeably. I've attached the results with the issues as an excel
[MasonLineups2_25_21.xlsx](https://github.com/jflancer/bigballR/files/6046858/MasonLineups2_25_21.xlsx)
 file here. Thanks for this great package!

Thanks,
Matt

**Comment by jflancer** [comment]
Hey Matt thanks for reaching out. I just tried reproducing the error and am getting slightly different results from the excel file you sent. I don't see any of the zero minute lineups. Here's the code I ran:

```
sched <- get_team_schedule(season = "2020-21", team.name = "George Mason")
pbp <- get_play_by_play(sched$Game_ID)
lins <- get_lineups(pbp, F)
```

If this is still an issue would you mind providing the code that you ran? I'll close this issue for now.
