### ISSUE TITLE
Using bigballR w/ ncaahoopR

### ISSUE THREAD

**Issue by lbenz730** [jflancer/bigballR#2]
Hey Jake,

Great package! I am enjoying working with `bigballR` and have some ideas of how to use it in conjunction with my ```ncaahoopR``` package. One thing I noticed is that we are both using a data frame called ```ids``` in our respective packages. Hence, when you load one of our packages after the other, it renders the first package's functionality limited. I'm not sure if you want to change the name of the `ids` data frame or if you have some other suggestion on how to work around this, but I just thought I would bring it to your attention.

Thanks,
Luke

**Comment by jflancer** [comment]
Thanks, Luke! I'll change the name of my ids dataset to teamids, as that is probably easiest.

Jake
