### ISSUE TITLE
Error running get_team_roster and get_team_schedule

### ISSUE THREAD

**Issue by ehrenj1** [jflancer/bigballR#25]
Hi Jake,

I was getting an error when I try to use the get_team_roster and get_team_schedule functions and it is caused by the following line:
file_url <- url(url_text, headers = c("User-Agent" = "My Custom User Agent"))

![image](https://user-images.githubusercontent.com/57914740/144163009-bbf8ec34-1345-4c01-95d0-7ce31b3d5e38.png)

I just reinstalled the package and updated all the necessary packages that needed update.  Any idea what could be causing this?  Thanks in advance!

Justin

**Comment by evanmiyakawa** [comment]
Not entirely sure what is causing the problem here, but you only need either `team.id` OR `season` and `team.name` arguments.

**Comment by ehrenj1** [comment]
Hi Evan,

Thanks for the response. I am still getting that error even after changing
the inputs:
[image: image.png]

It seems like it is an issue with that "url" function.  Do you know what
package that is a part of? It looks like the url package that my session is
using does not have "headers" as an input, so I am guessing it is maybe
using a different "url" function.
[image: image.png]

Thanks,
Justin

**Comment by evanmiyakawa** [comment]
I can't see your attached image.

**Comment by ehrenj1** [comment]
Alright I have tried attaching it as an image.  Let me know if it works.
