### ISSUE TITLE
get_team_schedule_error

### ISSUE THREAD

**Issue by dylangrafius** [jflancer/bigballR#34]
Hello,

I like to use this package for all teams in division I, II, and III but I've noticed that sometimes the schedule function gives me this output:

Parsing Schedule
Error in while (!substr(t[j], 1, i) %in% bigballR::teamids$Team && i <=  : 
  missing value where TRUE/FALSE needed

Is there anything that can be done to avoid this error in the future?

**Comment by evanmiyakawa** [comment]
Can you send some example code that led to this error?

**Comment by dylangrafius** [comment]
get_team_schedule(542947)

**Comment by dylangrafius** [comment]
I have about 40-50 other lines of code that give that same output if you want me to send those as well.

**Comment by evanmiyakawa** [comment]
Are you using the latest version of `bigballR::teamids`? `542947` is not an ID

**Comment by dylangrafius** [comment]
No, that’s a division II team ID from the NCAA website.

**Comment by dylangrafius** [comment]
And what's crazy is that the get_play_by_play function works for individual box scores. What I think may be the problem is these teams have games that are exhibition games. On their NCAA team pages it has this indicator at the bottom:

*Contest exempted and does not count toward season record or statistics for [INSERT TEAM] only.

Do you think there is any way around this?

**Comment by dylangrafius** [comment]
And you can even use that particular team ID to get the roster! So the issue is that the 50 teams (in D2) that have games that don't count messes up the schedule scraping and parsing function.

**Comment by evanmiyakawa** [comment]
I just pushed an update that should resolve this issue. 

`#install.packages("devtools")
devtools::install_github("jflancer/bigballR")`

**Comment by dylangrafius** [comment]
Thank you!
