### ISSUE TITLE
Issue in get_play_by_play

### ISSUE THREAD

**Issue by dylangrafius** [jflancer/bigballR#37]
Below is my code:
BAY_S <- get_team_schedule(542006)
BAY_PBP <- get_play_by_play(BAY_S$Game_ID)

And this is the error that I keep getting for Baylor PBP data:
Error in fix_call(vec_rbind(!!!dots, .names_to = .id)) : 
  could not find function "fix_call"

Do you know what could be causing this?

**Comment by evanmiyakawa** [comment]
I can't replicate the issue. Do you have the latest version of the package? It's also possible some of your package dependencies might be out of date.

**Comment by dylangrafius** [comment]
It seems that I do. I also just entered in the fix_call function on its own and that seems to have worked. Thank you.

**Comment by danmalter** [comment]
@dylangrafius - How did you fix this issue? I am also having this issue and have updated all libraries. I can't find a fix_call() function anywhere
