### ISSUE TITLE
stats.ncaa.org requires https:/

### ISSUE THREAD

**Issue by hoopsinsight** [jflancer/bigballR#49]
The "base_URL" object in the scrape_game function needs to be changed to https://stats.ncaa.org , I believe this is a recent issue as I used the existing function 3 weeks ago and it worked but now it does not.

**Comment by evanmiyakawa** [comment]
Thanks for flagging this, I'll get to it later today

**Comment by evanmiyakawa** [comment]
Closed with [this PR](https://github.com/jflancer/bigballR/pull/50)
