### ISSUE TITLE
get_team_schedule missing UConn - Alabama game

### ISSUE THREAD

**Issue by jrbarber37** [jflancer/bigballR#51]
For the following code:
UConn_schedule_2023_24 <- get_team_schedule(season = "2023-24", team.name = "UConn")

The Alabama game was not found.

Parsing Schedule
UConn complete--40/38 | games/ids found
Warning messages:
1: In pbp_ids[which(!is.na(pbp_ids))] <- if (length(new_ids) > 0) new_ids else NA :
  number of items to replace is not a multiple of replacement length
2: In box_ids[which(!is.na(box_ids))] <- if (length(game_ids) > 0) game_ids else NA :
  number of items to replace is not a multiple of replacement length

**Comment by evanmiyakawa** [comment]
I'll take a look tomorrow

**Comment by evanmiyakawa** [comment]
I think this got resolved on its own, must have been an NCAA issue

**Comment by jrbarber37** [comment]
Yes, this is working fine for me.  Thanks for checking.
