### ISSUE TITLE
get_team_schedule issue

### ISSUE THREAD

**Issue by dylangrafius** [jflancer/bigballR#52]
Code: 
> RMU_24_S <- get_team_schedule(561059)
Compiling Game IDs
=====================================================================================

Parsing Schedule
Error in Home[[i]] : subscript out of bounds

**Comment by jrbarber37** [comment]
I am seeing the same issuse: UConn_schedule_2023_24 <- get_team_schedule(season = "2023-24", team.name = "UConn")

Parsing Schedule
Error in Home[[i]] : subscript out of bounds

**Comment by evanmiyakawa** [comment]
NCAA just made some big updates to their UI and the underlying webpages, so it will take a bit of time to restructure the code to get things working again. I won't have time to do this till a little bit later in the offseason.

**Comment by jrbarber37** [comment]
Thanks for the update.

**Comment by jrbarber37** [comment]
Thank you for fixing this issue!

**Comment by try2catch32** [comment]
You updating bigballR would be much appreciated! The bigballR package is and has been my only resource as a volunteer data scientist for my local D3 college basketball team. Thank you in advance!

**Comment by try2catch32** [comment]
> Thanks for the update.
> […](#)

Hi jrbarber37. I was really proficient using the bigballr package before the NCAA changed its website. I saw you wrote "thanks for fixing the issue." Is there new documentation on how to get teams schedules and play by play data? I was once proficient and now can't access anything. Looking for help. Thanks in advance.
