### ISSUE TITLE
Data Issue LIU Schedule

### ISSUE THREAD

**Issue by jrbarber37** [jflancer/bigballR#57]
With this code.

LIU_schedule_2023_24 <- get_team_schedule(season = "2023-24", team.name = "LIU")

I am getting the following error.
Error in data.frame(Date = df$Date, Home = ifelse(!is.na(home_team), home_team,  : 
  arguments imply differing number of rows: 30, 29

Is there any known workaround for this type of data issue?

Thanks.

**Comment by cobrastats** [comment]
Evan mentioned the changes to the NCAA website in a [previous issue.](https://github.com/jflancer/bigballR/issues/52#issuecomment-2155214397)

**Comment by jrbarber37** [comment]
Thank you for getting back to me.  I did see the previous issue.  Since
that fix, all subsequent teams I searched worked except for LIU.  This
appears to be team-specific.

**Comment by evanmiyakawa** [comment]
Just pushed an update, should be fixed now. The issue was with handling cancelled games.

**Comment by jrbarber37** [comment]
The update fixed the problem I had with LIU's schedule.  Thanks for making
the fix!

John Barber
