### ISSUE TITLE
Looking for help. Can't access team schedules and play by play since NCAA changed website.

### ISSUE THREAD

**Issue by try2catch32** [jflancer/bigballR#60]
Hi. I was really proficient using the bigballr package before the NCAA changed its website. Is there new documentation on how to get teams schedules and play by play data? I was once proficient and now can't access anything. Looking for help. Thanks in advance.

**Comment by cobrastats** [comment]
Hey @try2catch32 

I'm happy to try to troubleshoot. Can you describe the issue?

I'd recommend too removing `bigballR` and reinstalling it (in order to let the updates to the code that Evan added take effect)

```r
#install.packages("devtools")
devtools::install_github("jflancer/bigballR")
```

**Comment by try2catch32** [comment]
Thank you! your recommendation worked! I feel silly I did not think of removing and reinstalling. Again, thank you!
