### ISSUE TITLE
Not an issue?  get_team_schedule for 2024-25

### ISSUE THREAD

**Issue by jrbarber37** [jflancer/bigballR#63]
Should I be able to get team schedules yet for 2024-25?

The following code: get_team_schedule(season = "2024-25", team.name = "Quinnipiac")

gives me the following message: Parsing Schedule
Error in new_game_ids[is.na(detail) | detail != "Canceled"] <- game_ids : 
  replacement has length zero

I believe I have the latest version:
devtools::install_github("jflancer/bigballR")
Skipping install of 'bigballR' from a github remote, the SHA1 (3dc1164f) has not changed since last install.
  Use `force = TRUE` to force installation

Sorry if I'm missing something obvious.

**Comment by evanmiyakawa** [comment]
I think this is an NCAA problem, their website is struggling right now with server load. Try this url for example:

https://stats.ncaa.org/season_divisions/18403/scoreboards?game_date=11%2F04%2F2024&conference_id=0&commit=Submit

**Comment by jrbarber37** [comment]
Thanks, Evan.  I can see that the NCAA site is struggling: This website is under heavy load (queue full)

**Comment by jrbarber37** [comment]
I can now get a schedule for UT Arlington whereby 1 of 30 games is returned.
UTArlington_schedule_2024_25 <- get_team_schedule(season = "2024-25", team.name = "UT Arlington")

However, when I use the following code to get play-by-play, 30 occurrences (15,720 records) of Game ID 5736787 are returned.
UTArlington_play_by_play_2024_25 <- get_play_by_play(UTArlington_schedule_2024_25$Game_ID)

Could this be somehow related to the following fix made on 8/12?

use NA game_ids when game is canceled. (PR #58)

**Comment by jrbarber37** [comment]
The same issue with Middle Tenn. 1 of 29 games returned, 29 get_play_by_play calls returned for game 5734927

**Comment by evanmiyakawa** [comment]
Just pushed a fix https://github.com/jflancer/bigballR/pull/64

**Comment by jrbarber37** [comment]
Thanks so much for making the changes!!
