### ISSUE TITLE
get_date_games removes (state) from team name

### ISSUE THREAD

**Issue by floydanalytics** [jflancer/bigballR#66]
The following line (and its away counterpart) in the `get_date_games` function:

`home_name = gsub(" [(].*[)]", "", home_team)`

removes the state from team names (e.g. Miami (OH), Miami (FL), and LMU (CA)) and these names no longer align with the teamids. In particular, the Miamis can no longer be differentiated.

**Comment by evanmiyakawa** [comment]
I'll take a look!

**Comment by evanmiyakawa** [comment]
Fixed! https://github.com/jflancer/bigballR/pull/67
