### ISSUE TITLE
Installation Troubles

### ISSUE THREAD

**Issue by yudaniel98** [jflancer/bigballR#9]
Hi I'm new to R so this may just be a dumb question, but when I enter

> #install.packages("devtools")
> devtools::install_github("jflancer/bigballR")

I get

Installing package into ‘C:/Users/Daniel/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'bigballR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: package 'colorspace' does not have a namespace
Execution halted
ERROR: lazy loading failed for package 'bigballR'
* removing 'C:/Users/Daniel/Documents/R/win-library/4.0/bigballR'
Error: Failed to install 'bigballR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Daniel/AppData/Local/Temp/RtmpQHsRj0/file23286df51a55/bigballR_0.1.0.tar.gz’ had non-zero exit status

**Comment by jflancer** [comment]
`ggplot2` is a dependency for this package, and it looks like you may not have a dependency for `ggplot2` installed. Please try running `install.packages("colorspace")`. Maybe also check out `https://stackoverflow.com/questions/28887446/r-error-on-installing-colorspace-for-ggplot2` if there are still issues
